

spring:
  config:
    activate:
      on-profile: docker

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/devwiki?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 50
      max-lifetime: 30000
      connection-timeout: 3000
      username: abcd
      password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        order_inserts: true
        jdbc:
          batch_size: 100
